---
language: php
os: linux
before_install: 
    - sudo apt update 
    - sudo apt upgrade -y 
install:
    - sudo apt install composer --assume-yes
    - composer install --no-interaction
    - composer require predis/predis
